# Generated by Django 5.2.1 on 2025-05-24 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='file_uploaded',
            field=models.FileField(upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
