# Generated by Django 5.2.1 on 2025-05-25 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0002_alter_pdfupload_file_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.CharField(blank=True, max_length=300)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadfile.pdfupload')),
            ],
        ),
        migrations.CreateModel(
            name='SharePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadfile.pdfupload')),
            ],
        ),
    ]
