# Generated by Django 5.2.1 on 2025-05-25 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0004_alter_sharepdf_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepdf',
            name='pdf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sharepdf', to='uploadfile.pdfupload'),
        ),
    ]
